#!/bin/bash

function displayhelp {
    echo "$0 [ --debug | --release ] [ --verbose ]"
}

DEBUG_SET=false
RELEASE_SET=false
VERBOSE_SET=false

while [ -n "$1" ]
do
    case "$1" in
	--debug)
	    DEBUG_SET=true
	    ;;

	--release)
	    RELEASE_SET=true
	    ;;

	--verbose)
	    VERBOSE_SET=true
	    ;;

	-h | --help)
	    displayhelp
	    exit
	    ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

VERBOSITY_SETTING=
if [ $VERBOSE_SET == true ]; then
    VERBOSITY_SETTING="VERBOSE=1"
fi

BUILD_TYPE=

if [ $RELEASE_SET == true ]; then
    BUILD_TYPE=Release
else
    BUILD_TYPE=Debug
fi

# Generate the makefile with cmake
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

# Build
make $VERBOSITY_SETTING
